### ISSUE TITLE
[<1.21.11] Stuck pixels appearing when on fire on the right top and the left top when Sodium installed

### ISSUE THREAD

**Issue by HyperFIare** [CaffeineMC/sodium#3098]
### Bug Description

Basically everytime im on fire two stuck pixels appear on the right and left top ive tried everything to fix it and first ive deleted every single mod and installed all of them on by one (same for the resource pack) and the problem didnt appear except when i added sodium back that made the problem appear again on my screen and it even happens on the latest version 0.6.13 of sodium. I also tested my hardware using different monitors and cables and the issue still persists.

### Reproduction Steps

You can reproduce this Bug by installing sodium and making your own character catch on fire and that makes the stuck pixels appear near the right and left top corner of your screen

### Log File

[latest.log](https://github.com/user-attachments/files/19615081/latest.log)

### Crash Report

[crash-2025-04-05_13.21.40-client.txt](https://github.com/user-attachments/files/19615077/crash-2025-04-05_13.21.40-client.txt)

**Comment by douira** [comment]
Can you show us a screenshot of this?

**Comment by HyperFIare** [comment]
> Can you show us a screenshot of this?
Yes of course it doesnt appear on screenshots so i made a photo

![Image](https://github.com/user-attachments/assets/d9173569-0370-4142-9cd0-d585a439fa0c)

**Comment by douira** [comment]
If it doesn't show up on screenshots idk how we can help you... Maybe your graphics card or driver is broken.

**Comment by HyperFIare** [comment]
> If it doesn't show up on screenshots idk how we can help you... Maybe your graphics card or driver is broken.
No like i mentioned i tested it on different monitors, different pcs and hdmi cables the problem only appears when the sodium mod is added in the mods folder.

**Comment by HyperFIare** [comment]
> If it doesn't show up on screenshots idk how we can help you... Maybe your graphics card or driver is broken.

Oh btw i finally managed to take a screenshot with the problem on it. Just fullscreen and look near top right carefully and you will see it

![Image](https://github.com/user-attachments/assets/601abd0a-98a8-4ba4-af2f-f7093af44728)

**Comment by douira** [comment]
Can you make sure it also happens when you only have sodium installed and no other mods? This seems like an instance of a bug we've had before but I currently can't find the issue report (if there is one).

**Comment by HyperFIare** [comment]
> Can you make sure it also happens when you only have sodium installed and no other mods? This seems like an instance of a bug we've had before but I currently can't find the issue report (if there is one).

I just removed every single mod except for Fabric API and Sodium and the issue still persists

**Comment by douira** [comment]
interesting

**Comment by oztommo** [comment]
I've also got this issue.
The stuck pixel can be seen near the top left - I tried to make the screenshots as clear as possible.

![Image](https://github.com/user-attachments/assets/65cb7c83-c094-45cc-b580-515f1d1eaf17)
![Image](https://github.com/user-attachments/assets/c05c5061-0ebc-465d-829e-9eb34c732161)

**Comment by douira** [comment]
It's the problem with sampling the fire texture out of bounds

**Comment by HyperFIare** [comment]
> It's the problem with sampling the fire texture out of bounds

Is it gonna be fixed in the later updates?

**Comment by FamineOLaymine** [comment]
I'm having this issue too only while Sodium is installed, severity seems to depend on game resolution. It's quite noticeable here (and more in person). I'll try editing the fire texture later to see if that can temporarily remedy this issue! (Update: resource packs do not change it)
You can see these at the top of each half of the fire.
![Image](https://github.com/user-attachments/assets/53b5390d-d2eb-49c5-bbb6-e2e5a404164f)

**Comment by Duskyth** [comment]
Any update on this? This issue still persists within the latest 1.21.1 build and isn't present in Embeddium, which would be a good alternative if other mods conflicted with Embeddium such as Veil.

**Comment by familiacastro028-beep** [comment]
Hi, I'm here to report this same problem. I get these pixels and I've attached a screenshot of where they appear. I tried vanilla Minecraft and they don't appear, only with sodium.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e07f7d4f-dffc-4c01-b272-d36d708c1e69" />
<img width="1632" height="167" alt="Image" src="https://github.com/user-attachments/assets/d6b7399a-17bd-475b-a93c-032f86c7ed5f" />

**Comment by douira** [comment]
This appears to have been resolved as of Minecraft 1.21.11.

**Comment by jellysquid3** [comment]
I don't think this issue should have been closed. Earlier versions of Minecraft don't use a large enough epsilon, but Sodium makes the problem much worse due to how it messes with UV coordinates, which is a legitimate regression.

**Comment by Lolothepro** [comment]
related to https://github.com/CaffeineMC/sodium/issues/3013

**Comment by LeEmokid** [comment]
<img width="5112" height="1356" alt="Image" src="https://github.com/user-attachments/assets/63be49dd-2607-4dc0-aeb4-feaeea04bcc7" />

<img width="1973" height="341" alt="Image" src="https://github.com/user-attachments/assets/7bd88fe3-14f8-48c2-a170-bfc6c75f51c6" />

Still an issue, ATM10 V8.1 with Sodium 0.8.13. Only appears when I am on fire, with and without shaders. May need to view picture in full screen to see it, it's much more noticeable in game.
